"""Install-topology helpers.

`detect_editable_install` answers: is `metaensemble` installed in editable
mode (e.g. `pip install -e .`) in the target Python interpreter?

The question matters because MetaEnsemble's documented install promise is
that once `metaensemble user-setup` has vendored the runtime, the dev
source tree is dispensable. That promise only holds when the Python
pinned in `~/.metaensemble/runtime/bin/me-run` has a non-editable
(wheel-installed) `metaensemble` distribution. An editable install
leaves the runner load-bearing on the dev tree — delete the source and
the runner can no longer resolve `import metaensemble`.

We read PEP 610 `direct_url.json` from the distribution's dist-info,
which is the canonical record of how a distribution was installed.
`dir_info.editable: true` marks an editable install.

This module is consumed by:
- `metaensemble user-setup` — prints a non-blocking warning when the
  active interpreter is editable, so the user knows the install will be
  load-bearing on the source tree before it happens.
- `metaensemble doctor` C12 — inspects the pinned Python from `me-run`
  and surfaces the same state on every health check.
"""
from __future__ import annotations

import json
import re
import subprocess  # nosec B404
import sys
from dataclasses import dataclass
from pathlib import Path


# Self-contained Python program that runs in the target interpreter and
# emits a single JSON line on stdout. Kept inline so callers do not need
# to ship a separate script file alongside the package.
_PROBE = r"""
import json
try:
    from importlib.metadata import distribution, PackageNotFoundError
except ImportError:
    print(json.dumps({"installed": False, "editable": False, "source": None}))
    raise SystemExit(0)
try:
    dist = distribution("metaensemble")
except PackageNotFoundError:
    print(json.dumps({"installed": False, "editable": False, "source": None}))
    raise SystemExit(0)
direct = dist.read_text("direct_url.json")
if direct is None:
    print(json.dumps({"installed": True, "editable": False, "source": None}))
    raise SystemExit(0)
try:
    payload = json.loads(direct)
except json.JSONDecodeError:
    print(json.dumps({"installed": True, "editable": False, "source": None}))
    raise SystemExit(0)
dir_info = payload.get("dir_info") or {}
url = payload.get("url") or ""
source = url[len("file://"):] if url.startswith("file://") else url
print(json.dumps({
    "installed": True,
    "editable": bool(dir_info.get("editable")),
    "source": source or None,
}))
"""


@dataclass(frozen=True)
class InstallTopology:
    """Result of `detect_editable_install` for a single Python interpreter."""

    python_executable: str
    installed: bool
    editable: bool
    source: str | None


def detect_editable_install(python_executable: str | None = None) -> InstallTopology:
    """Determine whether `metaensemble` is installed in editable mode in
    the given Python interpreter (default: the active one).

    Never raises. Returns InstallTopology(installed=False) when the
    package is missing, the interpreter is missing, or the metadata is
    unreadable. Probing is bounded by a 10-second timeout so a hung or
    very slow interpreter cannot stall the doctor.
    """
    if python_executable is None:
        python_executable = sys.executable
    try:
        result = subprocess.run(  # nosec B603
            [python_executable, "-c", _PROBE],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return InstallTopology(python_executable, False, False, None)
    if result.returncode != 0:
        return InstallTopology(python_executable, False, False, None)
    try:
        data = json.loads(result.stdout.strip())
    except json.JSONDecodeError:
        return InstallTopology(python_executable, False, False, None)
    return InstallTopology(
        python_executable=python_executable,
        installed=bool(data.get("installed")),
        editable=bool(data.get("editable")),
        source=data.get("source"),
    )


# The `me-run` shell script is generated by `_runner_text` in installer.py
# and always has the shape `exec '<python>' -m metaensemble.cli "$@"` (or
# `exec <python>` when no quoting is needed). We pin to that shape rather
# than to a less specific regex so a future change to the runner template
# fails loudly here instead of silently extracting the wrong path.
_RUNNER_PYTHON_RE = re.compile(
    r"^exec\s+(?:'([^']+)'|([^\s]+))\s+-m\s+metaensemble",
    re.MULTILINE,
)


def runner_python_path(
    runner_path: Path | None = None,
    home: Path | None = None,
) -> str | None:
    """Read `~/.metaensemble/runtime/bin/me-run` and return the pinned
    Python interpreter path. Returns None when the runner is missing or
    its shape no longer matches the generated template."""
    if runner_path is None:
        root = home or Path.home()
        runner_path = root / ".metaensemble" / "runtime" / "bin" / "me-run"
    if not runner_path.exists():
        return None
    try:
        text = runner_path.read_text()
    except OSError:
        return None
    match = _RUNNER_PYTHON_RE.search(text)
    if not match:
        return None
    return match.group(1) or match.group(2)


def editable_install_notice(topology: InstallTopology, layout: str) -> str:
    """Render the warning printed by `user-setup` and C12 when the target
    interpreter's `metaensemble` distribution is installed editable."""
    source = topology.source or "<source path unknown>"
    return (
        f"[notice] Editable install of `metaensemble` detected in:\n"
        f"           {topology.python_executable}\n"
        f"         Source: {source}\n"
        f"\n"
        f"         The runner at `~/.metaensemble/runtime/bin/me-run` will be\n"
        f"         pinned to this Python, so the install is load-bearing on\n"
        f"         the source tree above. That contradicts the documented\n"
        f"         \"install once, dev tree dispensable\" promise. To get a\n"
        f"         dev-tree-independent install, build a wheel and install\n"
        f"         it into a non-editable interpreter, then run user-setup\n"
        f"         from that interpreter:\n"
        f"\n"
        f"             python -m build --wheel\n"
        f"             <other-python> -m pip install dist/metaensemble-*.whl\n"
        f"             <other-python> -m metaensemble user-setup --layout={layout}\n"
        f"\n"
        f"         Proceeding with the editable install."
    )
